import React from'react';import{beforeEach,describe,expect,it,vi}from'vitest';import{fireEvent,render,screen,waitFor}from'@testing-library/react';import App from'./App';import{HISTORY_STORAGE_KEY,STORAGE_KEY}from'./model';
const record=(number,patch={})=>({group:`Group ${number}`,option:`Option ${number}`,mode:'sequential',time:new Date(2026,0,1,0,number).toISOString(),...patch});
beforeEach(()=>{localStorage.clear();vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true,addEventListener:vi.fn(),removeEventListener:vi.fn()})));vi.stubGlobal('confirm',()=>true)});
describe('application interactions',()=>{
 it('runs sequential selection and enables option wheel',async()=>{render(<App/>);const option=screen.getByRole('button',{name:/Game wheel/});expect(option.disabled).toBe(true);fireEvent.click(screen.getByText('Spin person'));await waitFor(()=>expect(option.disabled).toBe(false));fireEvent.click(screen.getByText('Spin game'));await waitFor(()=>expect(screen.getByText(/—/)).toBeTruthy())});

 it('uses configured nouns in controls, stages, instructions, and accessible names',()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify({metadata:{groupNoun:'category',optionNoun:'meal'},groups:[{id:'food',label:'Cuisine',color:'#ffffff',options:[{id:'taco',label:'Tacos',color:'#ffffff'}]}]}));render(<App/>);expect(screen.getByRole('button',{name:'Spin category'})).toBeTruthy();expect(screen.getByRole('button',{name:'Spin meal'})).toBeTruthy();expect(screen.getByText('01 · CATEGORY')).toBeTruthy();expect(screen.getByText('02 · MEAL')).toBeTruthy();expect(screen.getByText('First category. Then meal.')).toBeTruthy();expect(screen.getByRole('button',{name:/Category wheel/})).toBeTruthy();expect(screen.getByRole('button',{name:/Meal wheel/})).toBeTruthy();expect(screen.getByRole('button',{name:'＋ Add category'})).toBeTruthy();expect(screen.getByRole('button',{name:'＋ Add meal'})).toBeTruthy();expect(screen.getByRole('textbox',{name:'Category name'})).toBeTruthy();expect(screen.getByRole('textbox',{name:'Meal in Cuisine'})).toBeTruthy()});
 it('supports automatic two-stage spin control',async()=>{render(<App/>);fireEvent.click(screen.getByText('Spin both'));await waitFor(()=>expect(screen.getByText(/—/)).toBeTruthy())});
 it('edits configuration and persists locally',async()=>{render(<App/>);const names=screen.getAllByLabelText('Person name');fireEvent.change(names[0],{target:{value:'Dinner'}});await waitFor(()=>expect(JSON.parse(localStorage.getItem(STORAGE_KEY)).groups[0].label).toBe('Dinner'))});
 it('operates a wheel by keyboard',async()=>{render(<App/>);const wheel=screen.getByRole('button',{name:/Person wheel/});fireEvent.keyDown(wheel,{key:'Enter'});fireEvent.click(wheel);await waitFor(()=>expect(screen.getByText(/Selected:/)).toBeTruthy())});
 it('honors reduced motion with immediate result',async()=>{render(<App/>);fireEvent.click(screen.getByText('Spin person'));await waitFor(()=>expect(screen.getAllByText(/Selected:/).length).toBe(1))});
 it('restores configuration from local persistence',()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify([{id:'food',label:'Food',color:'#ffffff',options:[]}])) ;render(<App/>);expect(screen.getAllByDisplayValue('Food')[0]).toBeTruthy()});
 it('loads valid history from local persistence',()=>{localStorage.setItem(HISTORY_STORAGE_KEY,JSON.stringify([record(1)]));render(<App/>);expect(screen.getByText('Group 1')).toBeTruthy();expect(screen.getByText('Option 1')).toBeTruthy()});
 it('discards malformed stored history entries',async()=>{localStorage.setItem(HISTORY_STORAGE_KEY,JSON.stringify([record(1),{group:'Broken',option:'No timestamp',mode:'sequential'}]));render(<App/>);expect(screen.getByText('Group 1')).toBeTruthy();expect(screen.queryByText('Broken')).toBeNull();await waitFor(()=>expect(JSON.parse(localStorage.getItem(HISTORY_STORAGE_KEY))).toEqual([record(1)]))});
 it('retains only the latest 30 loaded records',async()=>{localStorage.setItem(HISTORY_STORAGE_KEY,JSON.stringify(Array.from({length:35},(_,i)=>record(i))));const {container}=render(<App/>);expect(container.querySelectorAll('.history li')).toHaveLength(30);expect(screen.getByText('Group 0')).toBeTruthy();expect(screen.queryByText('Group 30')).toBeNull();await waitFor(()=>expect(JSON.parse(localStorage.getItem(HISTORY_STORAGE_KEY))).toHaveLength(30))});
 it('clears displayed and persisted history together',async()=>{localStorage.setItem(HISTORY_STORAGE_KEY,JSON.stringify([record(1)]));render(<App/>);fireEvent.click(screen.getByText('Clear'));expect(screen.getByText(/No selections yet/)).toBeTruthy();await waitFor(()=>expect(JSON.parse(localStorage.getItem(HISTORY_STORAGE_KEY))).toEqual([]))});
});
