import React from 'react';
import { describe,expect,it,vi } from 'vitest';
import { fireEvent,render,screen,waitFor,within } from '@testing-library/react';
import { MODE_METADATA,Modes,SelectionMode,STATUS_LABELS,STATUS_MEANINGS } from './Modes';
const groups=[{id:'a',label:'A',color:'#f00',options:[{id:'1',label:'One'},{id:'2',label:'Two'}]},{id:'b',label:'B',color:'#0f0',options:[{id:'3',label:'Three'}]}];
describe('mode components',()=>{
 it('drives every gallery card from playable metadata and returns to default',()=>{render(<Modes groups={groups} onResult={()=>{}} reducedMotion/>);expect(screen.getAllByRole('button',{name:/^(Play this mode|Try interactive preview)$/})).toHaveLength(MODE_METADATA.length);fireEvent.click(screen.getAllByRole('button',{name:/^(Play this mode|Try interactive preview)$/})[4]);expect(screen.getByRole('heading',{name:'Tournament',level:2})).toBeTruthy();fireEvent.click(screen.getByText('Return to default'));expect(screen.getByRole('heading',{name:'Sequential wheels',level:2})).toBeTruthy()});
 it('defines consistent status vocabulary and classifies the generic linked visualization as a preview',()=>{expect(STATUS_LABELS).toEqual({implemented:'Implemented',preview:'Interactive preview',concept:'Concept'});expect(Object.keys(STATUS_MEANINGS)).toEqual(Object.keys(STATUS_LABELS));expect(MODE_METADATA.find(mode=>mode.id==='linked')).toMatchObject({status:'preview',description:expect.stringContaining('automatic two-stage spin')})});
 it('keeps status badges and gallery actions consistent',()=>{render(<Modes groups={groups} onResult={()=>{}} reducedMotion/>);for(const mode of MODE_METADATA){const card=screen.getByRole('heading',{name:new RegExp(`^${mode.name}`),level:3}).closest('article');expect(within(card).getByText(STATUS_LABELS[mode.status]).classList.contains(mode.status)).toBe(true);if(mode.status==='concept')expect(within(card).queryByRole('button')).toBeNull();else expect(within(card).getByRole('button',{name:mode.status==='preview'?'Try interactive preview':'Play this mode'})).toBeTruthy()}});
 it('renders a concept as a noninteractive design card rather than a playable experience',()=>{render(<SelectionMode mode={{id:'future',name:'Future mode',kind:'motion',status:'concept'}} groups={groups} onResult={()=>{}}/>);expect(screen.getByText(/noninteractive design concept/)).toBeTruthy();expect(screen.queryByRole('button')).toBeNull()});
 for(const mode of MODE_METADATA.filter(x=>!['sequential','nested'].includes(x.id))){
  it(`${mode.name} produces a normalized result`,async()=>{const result=vi.fn();render(<SelectionMode mode={mode} groups={groups} onResult={result} reducedMotion/>);const button=screen.getByRole('button',{name:mode.kind==='wheel'?new RegExp(`${mode.name} wheel`):`Run ${mode.name} preview`});fireEvent.click(button);await waitFor(()=>expect(result).toHaveBeenCalled());expect(result.mock.calls[0][0]).toMatchObject({mode:mode.id,groupId:expect.any(String),optionId:expect.any(String),selections:expect.any(Array),time:expect.any(String)})});
 }
 it('linked wheels always select an option from the chosen group',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA.find(mode=>mode.id==='linked')} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Run Linked wheels preview'));await waitFor(()=>expect(result).toHaveBeenCalled());const record=result.mock.calls[0][0];expect(groups.find(g=>g.id===record.groupId).options.some(o=>o.id===record.optionId)).toBe(true)});
 it('sequential wheels preserve the group-to-option relationship',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin both'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(groups.find(g=>g.id===result.mock.calls[0][0].groupId).options.some(o=>o.id===result.mock.calls[0][0].optionId)).toBe(true)});
 it('ignores duplicate combined spins while either wheel is active',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={groups} onResult={result}/>);const combined=screen.getByText('Spin both');fireEvent.click(combined);fireEvent.click(combined);await waitFor(()=>expect(screen.getByRole('button',{name:/Option wheel/}).disabled).toBe(false),{timeout:3000});fireEvent.click(combined);await waitFor(()=>expect(result).toHaveBeenCalledTimes(1),{timeout:3000})},7000);
 it('nested wheels rotate outer and inner rings independently',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[2]} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Rotate both rings'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(screen.getByRole('button',{name:/Outer ring/})).toBeTruthy();expect(screen.getByRole('button',{name:/Inner ring/})).toBeTruthy()});
 it('skips empty groups when Spin both runs',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={[{id:'empty',label:'Empty',options:[]},groups[0]]} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin both'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(result.mock.calls[0][0]).toMatchObject({groupId:'a',optionId:expect.any(String)})});
 it('disables all two-stage controls when no group has a valid option',()=>{render(<SelectionMode mode={MODE_METADATA[0]} groups={[{id:'empty',label:'Empty',options:[]},{id:'blank',label:'Blank',options:[{id:'x',label:' '}]}]} onResult={()=>{}} reducedMotion/>);expect(screen.getByText('Spin group').disabled).toBe(true);expect(screen.getByText('Spin both').disabled).toBe(true)});
 it('clears a selected group after its last option is deleted',async()=>{const result=vi.fn();const {rerender}=render(<SelectionMode mode={MODE_METADATA[0]} groups={[groups[0]]} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin group'));await waitFor(()=>expect(screen.getByText('Spin option').disabled).toBe(false));rerender(<SelectionMode mode={MODE_METADATA[0]} groups={[{...groups[0],options:[]}]} onResult={result} reducedMotion/>);await waitFor(()=>expect(screen.getByText('Spin option').disabled).toBe(true));expect(screen.getByText('Spin both').disabled).toBe(true)});
 it('honors disabled state',()=>{render(<SelectionMode mode={MODE_METADATA[4]} groups={groups} onResult={()=>{}} reducedMotion disabled/>);expect(screen.getByText('Run Tournament preview').disabled).toBe(true)});
});
