import React from 'react';
import { describe,expect,it,vi } from 'vitest';
import { fireEvent,render,screen,waitFor } from '@testing-library/react';
import { MODE_METADATA,Modes,SelectionMode,STATUS_LABELS } from './Modes';
const groups=[{id:'a',label:'A',color:'#f00',options:[{id:'1',label:'One'},{id:'2',label:'Two'}]},{id:'b',label:'B',color:'#0f0',options:[{id:'3',label:'Three'}]}];
describe('mode components',()=>{
 it('drives every gallery card from playable metadata and returns to default',()=>{render(<Modes groups={groups} onResult={()=>{}} reducedMotion/>);expect(screen.getAllByText('Try this mode')).toHaveLength(MODE_METADATA.length);fireEvent.click(screen.getAllByText('Try this mode')[4]);expect(screen.getByRole('heading',{name:'Tournament',level:2})).toBeTruthy();fireEvent.click(screen.getByText('Return to default'));expect(screen.getByRole('heading',{name:'Sequential wheels',level:2})).toBeTruthy()});
 it('uses distinct status labels and defines linked wheels as implemented two-stage spins',()=>{expect(STATUS_LABELS).toEqual({implemented:'Playable',planned:'Preview',concept:'Concept'});expect(MODE_METADATA.find(mode=>mode.id==='linked')).toMatchObject({status:'implemented',description:expect.stringContaining('automatic two-stage spin')})});
 for(const mode of MODE_METADATA.filter(x=>!['sequential','nested'].includes(x.id))){
  it(`${mode.name} produces a normalized result`,async()=>{const result=vi.fn();render(<SelectionMode mode={mode} groups={groups} onResult={result} reducedMotion/>);const button=screen.getByRole('button',{name:mode.kind==='wheel'?new RegExp(`${mode.name} wheel`):`Play ${mode.name}`});fireEvent.click(button);await waitFor(()=>expect(result).toHaveBeenCalled());expect(result.mock.calls[0][0]).toMatchObject({mode:mode.id,groupId:expect.any(String),optionId:expect.any(String),selections:expect.any(Array),time:expect.any(String)})});
 }
 it('linked wheels always select an option from the chosen group',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA.find(mode=>mode.id==='linked')} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Play Linked wheels'));await waitFor(()=>expect(result).toHaveBeenCalled());const record=result.mock.calls[0][0];expect(groups.find(g=>g.id===record.groupId).options.some(o=>o.id===record.optionId)).toBe(true)});
 it('sequential wheels preserve the group-to-option relationship',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin both'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(groups.find(g=>g.id===result.mock.calls[0][0].groupId).options.some(o=>o.id===result.mock.calls[0][0].optionId)).toBe(true)});
 it('ignores duplicate combined spins while either wheel is active',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={groups} onResult={result}/>);const combined=screen.getByText('Spin both');fireEvent.click(combined);fireEvent.click(combined);await waitFor(()=>expect(screen.getByRole('button',{name:/Option wheel/}).disabled).toBe(false),{timeout:3000});fireEvent.click(combined);await waitFor(()=>expect(result).toHaveBeenCalledTimes(1),{timeout:3000})},7000);
 it('nested wheels rotate outer and inner rings independently',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[2]} groups={groups} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Rotate both rings'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(screen.getByRole('button',{name:/Outer ring/})).toBeTruthy();expect(screen.getByRole('button',{name:/Inner ring/})).toBeTruthy()});
 it('skips empty groups when Spin both runs',async()=>{const result=vi.fn();render(<SelectionMode mode={MODE_METADATA[0]} groups={[{id:'empty',label:'Empty',options:[]},groups[0]]} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin both'));await waitFor(()=>expect(result).toHaveBeenCalled());expect(result.mock.calls[0][0]).toMatchObject({groupId:'a',optionId:expect.any(String)})});
 it('disables all two-stage controls when no group has a valid option',()=>{render(<SelectionMode mode={MODE_METADATA[0]} groups={[{id:'empty',label:'Empty',options:[]},{id:'blank',label:'Blank',options:[{id:'x',label:' '}]}]} onResult={()=>{}} reducedMotion/>);expect(screen.getByText('Spin group').disabled).toBe(true);expect(screen.getByText('Spin both').disabled).toBe(true)});
 it('clears a selected group after its last option is deleted',async()=>{const result=vi.fn();const {rerender}=render(<SelectionMode mode={MODE_METADATA[0]} groups={[groups[0]]} onResult={result} reducedMotion/>);fireEvent.click(screen.getByText('Spin group'));await waitFor(()=>expect(screen.getByText('Spin option').disabled).toBe(false));rerender(<SelectionMode mode={MODE_METADATA[0]} groups={[{...groups[0],options:[]}]} onResult={result} reducedMotion/>);await waitFor(()=>expect(screen.getByText('Spin option').disabled).toBe(true));expect(screen.getByText('Spin both').disabled).toBe(true)});
 it('honors disabled state',()=>{render(<SelectionMode mode={MODE_METADATA[4]} groups={groups} onResult={()=>{}} reducedMotion disabled/>);expect(screen.getByText('Play Tournament').disabled).toBe(true)});
});
